version: '3.4'

x-common-config: &common_config
  image: squad/local
  build:
    context: .
  volumes:
    - home:/app
  environment:
    - SQUAD_CELERY_BROKER_URL=amqp://rabbitmq
    - XDG_DATA_HOME=/app

volumes:
  home:

services:
  rabbitmq:
    image: rabbitmq
    restart: always

  dbmigrate:
    <<: *common_config
    command: squad-admin migrate
    deploy:
      restart_policy:
        condition: none

  web:
    <<: *common_config
    command: squad --fast --bind 0.0.0.0:8080
    ports:
      - '8080:8080'
    restart: always

  worker:
    <<: *common_config
    command: squad-worker
    restart: always

  listener:
    <<: *common_config
    command: squad-listener
    restart: always

  scheduler:
    <<: *common_config
    command: squad-scheduler
    restart: always